sudo: true

language: go

go:
  - "1.15.x"

service:
  - docker

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: build docker image
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_5gc-dev
      - export VERSION=0.1.19
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/_output/bin/goserv -gcflags all=-trimpath=${GOPATH} -asmflags all=-trimpath=${GOPATH} -tags=v1 ./cmd/...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DHUBREPO:$VERSION -f build/Dockerfile .
      - docker images
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:latest
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $DHUBREPO
    - stage: test
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_5gc-dev
      - export VERSION=0.1.19
      - docker run -d -p 127.0.0.1:8080:80 --name hello $DHUBREPO:$VERSION
      - docker ps | grep -q hello
      # - curl -vsf 'http://127.0.0.1:8080/index.html' &> /dev/stdout
